spring.application.name=APIGateway
server.port=9091
 
spring.cloud.gateway.server.webflux.routes[0].id=deptservice
spring.cloud.gateway.server.webflux.routes[0].predicates=Path=/dept/**
spring.cloud.gateway.server.webflux.routes[0].uri=lb://deptservice
 
spring.cloud.gateway.server.webflux.routes[1].id=employeeservice
spring.cloud.gateway.server.webflux.routes[1].predicates=Path=/emps/**
spring.cloud.gateway.server.webflux.routes[1].uri=lb://employeeservice
spring.cloud.config.import-check.enabled=false
eureka.instance.prefer-ip-address=true
